# Generated by Django 3.1.5 on 2021-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech_api', '0003_speechapimodel_vocab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechapimodel',
            name='vocab',
            field=models.TextField(blank=True),
        ),
    ]
