# Generated by Django 3.1.5 on 2021-01-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210113_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='api_server/static/photo'),
        ),
    ]
