# Generated by Django 3.1.5 on 2021-01-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
