# Generated by Django 3.1.5 on 2021-02-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='encoded_data',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='extension',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='done',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='photo',
        ),
        migrations.AddField(
            model_name='todo',
            name='model',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
