# Generated by Django 3.1.5 on 2021-02-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210202_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='extension',
            field=models.CharField(max_length=300),
        ),
    ]
