# Generated by Django 3.1.5 on 2021-02-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20210202_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='encoded_data',
            field=models.TextField(),
        ),
    ]
