# Generated by Django 3.1.5 on 2021-02-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20210202_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='extension',
            new_name='ext',
        ),
    ]
